name: Test Build and Publish Alpha

on:
  push:
    branches:
      - main

jobs:
  test-build-alpha:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout ğŸ›
        uses: actions/checkout@v4

      - name: Setup node env ğŸ—
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org/"
          cache: 'npm'

      - name: Add npm registry
        run: npm config set registry https://registry.npmjs.org/

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm run test

      - name: Build packages
        run: |
          npm run build
          echo "Finished running build"

      - name: publish-alpha
        env:
          NPM_AUTH: ${{ secrets.NPM_AUTH }}
        run: |
          npm config ls -l
          npm version prerelease --preid=alpha.$(git rev-parse --short HEAD) --no-git-tag-version
          npm publish --tag alpha
          echo "Finished running publish alpha"

      - name: cleanup
        if: always()
        run: if [ -e .npmrc ]; then rm .npmrc; fi 