name: hand-drawn-ui

on:
  push:
    branches:
      - main
      - publish

jobs:
  test-build-package:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout üõé
        uses: actions/checkout@v4

      - name: Setup node env üèó
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org/"
          cache: 'npm'

      - name: Add npm registry
        run: npm config set registry https://registry.npmjs.org/

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm run test

      - name: Build packages
        run: |
          npm run build
          echo "Finished running build"

      - name: release-publish
        if: github.ref == 'refs/heads/publish'
        env:
          NPM_AUTH: ${{ secrets.NPM_AUTH }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HUSKY: 0
        run: |
          cp ./package.json ./dist/
          npm run release

      - name: publish-alpha
        env:
          NPM_AUTH: ${{ secrets.NPM_AUTH }}
        run: |
          npm config ls -l
          npm version prerelease --preid=alpha.$(git rev-parse --short HEAD) --no-git-tag-version
          npm publish --tag alpha
          echo "Finished running publish alpha"

      - name: cleanup
        if: always()
        run: if [ -e .npmrc ]; then rm .npmrc; fi

      - name: Create Pull Request
        if: github.ref == 'refs/heads/publish'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [[ $(git log --format=%an | head -1 ) == 'semantic-release-bot' ]]; then
            echo 'Publishing log detected. Raising PRs...'
            gh pr create --base main  --head publish --title "chore: version bump to $(cat package.json | jq -r '.version') [skip ci]" --body ""
          else 
            echo 'Publishing skipped.'
          fi
